Python 3.12.2 (tags/v3.12.2:6abddd9, Feb  6 2024, 21:26:36) [MSC v.1937 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> nama=("Rido' Ul Ambari")
... umur=int(("18"))
... alamat=("Rancak, Praya")
... lulusan=("SMAN 1 Terara")
... agama=("Islam")
... nim=("SI20230030")
... tgl=("09-10-2005")
... nomor=int(("+6285337272912"))
... email=("tanajmen@gamil.com")
... 
... print("=="*14)
... print("   = BIODATA =") 
... print("    ----------")
... print(">  NAMA      :", nama    )
... print(">  NIM       :", nim     )
... print(">  UMUR      :", umur    )
... print(">  TGL LAHIR :", tgl    )
... print(">  ALAMAT    :", alamat  )
... print(">  AGAMA     :", agama   )
... print(">  LULUSAN   :", lulusan )
... print(">  NOMOR     :", nomor )
... print(">  E-MAIL    :", email)
